use_frameworks!

target 'ZPNavationBar_Example' do
  pod 'ZPNavationBar', :path => '../'

  target 'ZPNavationBar_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
